### ISSUE TITLE
About A mod B ==1 operation

### ISSUE THREAD

**Issue by ugrkm** [ozansz/logisim-testbench#1]
Hello,
In the pdf it says that when B is 0 take the value of A.  As a result, when B is 0 and A is equal to 1 Y should be also 1. Do I have a mistake here ?
Best

**Comment by ozansz** [comment]
Hi,

I have checked the spec in PDF again, I missed the note about the ambiguity of A mod B when B is zero.

I just have fixed the test configuration of Lab-1 in the examples/ directory. The test vector generator script works correctly.

Thanks for notifying me about the bug.
